ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "faster"
  site-url: "https://masapasa.github.io/faster/"
  description: "Dien-Hoa AI Blog"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/masapasa/faster/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/masapasa/faster/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
